services:
  mitm-js-proxy:
    build: .
    container_name: suplantar-proxy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PROXY_PORT}:8080"
    volumes:
      - ./.http-mitm-proxy:/usr/src/app/.http-mitm-proxy
      - ./server.js:/usr/src/app/server.js:ro
      - ./package.json:/usr/src/app/package.json:ro
      - ./hosts.json:/usr/src/app/hosts.json:ro
      # Monta SOLO html para que refleje cambios al vuelo
      - ./html:/usr/src/app/html
